printf "     .     '     ,"
printf "       _________"
printf "    _ /_|_____|_\\ _"
printf "      '. \\   / .'"
printf "        '.\\ /.'"
printf "          '.'     💎 Ruby is ready. Let the gems flow!"