echo "  ╔════════════════════════════════════╗"
echo "  ║   LicenseFinder Installation 🔍    ║"
echo "  ╚════════════════════════════════════╝"
echo "     [✔] Gem fetched"
echo "     [✔] Dependencies resolved"
echo "     [✔] LicenseFinder ready to scan"
echo "✨ Your compliance scanner is now armed!"