"  ╔════════════════════════════════════╗"
"  ║   LicenseFinder Installation 🔍    ║"
"  ╚════════════════════════════════════╝"
"     [✔] Gem fetched"
"     [✔] Dependencies resolved"
"     [✔] LicenseFinder ready to scan"
"✨ Your compliance scanner is now armed!"